Dionysus/Models/AuctionItem.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Runtime.Serialization;

namespace Dionysus.Models
{
    [DataContract]
    public class AuctionItem
    {
        [DataMember(Name = "id")]
        public int ID { get; set; }

        [DataMember(Name = "name")]
        public string Name { get; set; }

        [DataMember(Name = "description")]
        public string Description { get; set; }

        [DataMember(Name = "auctionEndTime")]        
        private string AuctionEndTimeJSON { get; set; }
        
        [IgnoreDataMember]
        [Display(Name = "Auction End Time")]
        public DateTime AuctionEndTime
        {
            get
            {
                if (AuctionEndTimeJSON != null)
                    return DateTime.Parse(AuctionEndTimeJSON, CultureInfo.InvariantCulture);
                else
                    return DateTime.Now;
            }
        }
    }
}

Dionysus/Models/ErrorViewModel.cs
namespace Dionysus.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Dionysus/Models/Offer.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace Dionysus.Models
{
    [DataContract]
    public class Offer
    {

        [DataMember(Name = "auctionItemID")]
        public int ID { get; set; }

        [Display(Name = "Buyer Name")]
        [DataMember(Name = "buyerName")]
        public string BuyerName { get; set; }

        [Display(Name = "Offer Amount")]
        [DataMember(Name = "offerAmount")]
        public decimal OfferAmount { get; set; }

        [DataMember(Name = "offerTime")]
        public DateTime OfferTime { get; set; }
    }
}

Dionysus/Controllers/AuctionItemsController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Dionysus.Models;
using System.Diagnostics;

namespace Dionysus.Controllers
{
    public class AuctionItemsController : Controller
    {
        // GET: AuctionItems
        public ActionResult Index()
        {
            List<AuctionItem> activeAuctionItems = AresAPIClient.AresWebAPIClient.FetchActiveAuctionItems().Result;
            return View(activeAuctionItems);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult About()
        {
            return View();
        }

    }
}

Dionysus/Controllers/OfferController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Dionysus.Models;
using Newtonsoft.Json;
using System.Net.Http;

namespace Dionysus.Controllers
{
    public class OfferController : Controller
    {

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult SubmitOffer()
        {
            return RedirectToAction("Index","AuctionItems");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,AuctionItemID,BuyerName,OfferAmount")] Offer offer)
        {
            string submitResult;
            offer.OfferTime = DateTime.Now;
            string offerJson = JsonConvert.SerializeObject(offer);
            HttpResponseMessage result = await AresAPIClient.AresWebAPIClient.SubmitOffer(offerJson);
            if (result.IsSuccessStatusCode)
            {
                submitResult = "success";
            } else if (result.StatusCode.ToString().Equals("901"))
            {
                submitResult = "auctionExpired";
            } else if (result.StatusCode.ToString().Equals("902"))
            {
                submitResult = "auctionInactive";
            }
            else
            {
                submitResult = "unknownError";
            }


            return RedirectToAction(nameof(OfferSubmitResult), new { id = submitResult });
        }

        public IActionResult OfferSubmitResult(string id)
        {
            string submitResult = "";
            switch (id)
            {
                case "success":
                    submitResult = "Congratulations - Your offer has been successfully submitted.";
                    break;
                case "auctionExpired":
                    submitResult = "Submitting the offer has failed as the auction end date has already passed at the time the offer was submitted.";
                    break;
                case "auctionInactive":
                    submitResult = "Submitting the offer has failed as the auction has been made inactive";
                    break;
                case "unknownError":
                    submitResult = "Unknown Error has occurred while trying to submit your offer - please contact Auction Inc.";
                    break;
                default:
                    submitResult = "";
                    break;
            }
            ViewData["SubmitResult"] = submitResult;
            return View();
        }

    }
}

Dionysus/Views/AuctionItems/Index.cshtml
@model IEnumerable<Dionysus.Models.AuctionItem>
@{
    ViewData["Title"] = "Active Auctions";
}
<h2>Currently active auctions</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AuctionEndTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AuctionEndTime)
                </td>
                <td>
                    <a asp-controller="Offer" asp-action="Create" asp-route-id="@item.ID">Submit an Offer</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Dionysus/Views/Offer/Create.cshtml
@model Dionysus.Models.Offer
@{
    ViewData["Title"] = "Create";
}
<h2>Create</h2>
<h4>Offer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BuyerName" class="control-label"></label>
                <input asp-for="BuyerName" class="form-control" />
                <span asp-validation-for="BuyerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfferAmount" class="control-label"></label>
                <input asp-for="OfferAmount" class="form-control" />
                <span asp-validation-for="OfferAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit Offer" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Dionysus/Views/Offer/OfferSubmitResult.cshtml
@{
    ViewData["Title"] = "Offer Submit Result";
}

<h2>Offer Submit Result</h2>

<p>@ViewData["SubmitResult"]</p>
<p>@ViewData["ID"]</p>

Dionysus/Views/Shared/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<p>A Client application for making auction offers on active auction items fetched from Ares Web-Application.</p>
<p>Created by Mait Raidmäe in August, 2017</p>
<p>E-mail: mait.raidmae@gmail.com</p>

Dionysus/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dionysus</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="AuctionItems" asp-action="Index" class="navbar-brand">Dionysus</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="AuctionItems" asp-action="About">About</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Dionysus</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>